"""Serialized randbats provenance must not carry a local filesystem layout.

`RandbatSourceMetadata` reaches much further than its name suggests: `source_metadata` is copied
onto every `RevealedPokemonBelief`, so a golden-corpus row carries it once per believed mon. With
absolute paths in it, a single generated corpus embeds the generating machine's home directory
hundreds of times over.

That is how `tests/data/golden_corpus_sample/rows.jsonl` came to hold a maintainer's home directory
in a PUBLIC repo, and why `tests/test_public_invariant.py::_ALLOWED_FOR_RULE` had to carve out an
exception instead: the rows are TAMPER-EVIDENT (each hashes its own payload), so the paths cannot be
scrubbed in place without forging those hashes — the corpus has to be regenerated by a writer that
never records them.

This pins the writer half of that. The regeneration itself is the other half.
"""

from __future__ import annotations

import json
import unittest

from pokezero.randbat import load_gen3_randbat_source_cached

from _showdown_root import requires_showdown, showdown_root


@requires_showdown()
class RandbatProvenancePortabilityTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.root = showdown_root()
        cls.source = load_gen3_randbat_source_cached(cls.root)

    def test_serialized_metadata_carries_no_absolute_paths(self) -> None:
        payload = self.source.metadata.to_payload()
        blob = json.dumps(payload)
        self.assertNotIn(str(self.root), blob, f"serialized provenance embeds the checkout root: {payload}")
        for marker in ("/Users/", "/home/", "C:\\\\Users"):
            self.assertNotIn(marker, blob, f"serialized provenance embeds a home directory: {payload}")

    def test_paths_are_relative_to_the_checkout_and_still_identify_the_artifact(self) -> None:
        """Portable does not mean empty: the artifact must still be identifiable.

        The relative paths say WHICH files were read; `source_hash` says which CONTENT. Dropping the
        absolute root loses only where the checkout happens to live on one machine.
        """
        payload = self.source.metadata.to_payload()
        self.assertIsNone(payload["showdown_root"])
        self.assertEqual(payload["sets_path"], "data/random-battles/gen3/sets.json")
        self.assertTrue(str(payload["generator_path"]).endswith("teams.js"))
        self.assertFalse(str(payload["generator_path"]).startswith("/"))
        self.assertTrue(payload["source_hash"], "source_hash is the real identity and must survive")

    def test_the_in_memory_object_keeps_the_absolute_paths(self) -> None:
        """Only the SERIALIZED form is scrubbed.

        The absolute paths are useful locally (diagnostics, error messages naming a real file), and
        the defect was never that they exist — only that they were written into a shipped artifact.
        Scrubbing the dataclass itself would trade one problem for a worse debugging experience.
        """
        self.assertEqual(str(self.source.metadata.showdown_root), str(self.root))
        self.assertTrue(str(self.source.metadata.sets_path).startswith(str(self.root)))


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
