"""Core interfaces for PokeZero self-play training."""

from .actions import (
    ACTION_COUNT,
    ActionCandidate,
    MOVE_ACTION_COUNT,
    SWITCH_ACTION_COUNT,
    canonical_switch_action_map,
    is_move_action,
    is_switch_action,
    move_action_candidates,
    switch_action_index_for_team_index,
    switch_action_candidates,
)
from .belief import (
    BattleBeliefSnapshot,
    CandidateSetSummary,
    PlayerBeliefView,
    PokemonSetSource,
    PublicBattleBeliefEngine,
    RevealedPokemonBelief,
)
from .collection import (
    CollectionMetrics,
    RolloutRecord,
    collect_rollouts,
    iter_rollout_records,
    read_rollout_records,
    rollout_record_from_dict,
    rollout_record_to_dict,
    summarize_records,
)
from .env import AsyncPokeZeroEnv, PokeZeroEnv, StepResult, TerminalState
from .local_showdown import LocalShowdownConfig, LocalShowdownEnv, LocalShowdownError
from .observation import ObservationSpec, PokeZeroObservationV0
from .showdown import (
    PlayerRelativeBattleState,
    PlayerRelativePublicEvent,
    ShowdownPokemon,
    ShowdownPublicEvent,
    ShowdownReplayState,
    ShowdownSubmission,
    detect_showdown_slot,
    normalize_for_player,
    observation_from_player_state,
    parse_showdown_replay,
    showdown_choice_for_action,
    showdown_submission_for_action,
    stable_category_id,
)

__all__ = [
    "ACTION_COUNT",
    "ActionCandidate",
    "AsyncPokeZeroEnv",
    "BattleBeliefSnapshot",
    "CandidateSetSummary",
    "CollectionMetrics",
    "MOVE_ACTION_COUNT",
    "ObservationSpec",
    "PokeZeroEnv",
    "PokeZeroObservationV0",
    "LocalShowdownConfig",
    "LocalShowdownEnv",
    "LocalShowdownError",
    "SWITCH_ACTION_COUNT",
    "PlayerRelativeBattleState",
    "PlayerRelativePublicEvent",
    "PlayerBeliefView",
    "PokemonSetSource",
    "PublicBattleBeliefEngine",
    "RevealedPokemonBelief",
    "RolloutRecord",
    "ShowdownPokemon",
    "ShowdownPublicEvent",
    "ShowdownReplayState",
    "ShowdownSubmission",
    "StepResult",
    "TerminalState",
    "canonical_switch_action_map",
    "collect_rollouts",
    "detect_showdown_slot",
    "is_move_action",
    "is_switch_action",
    "move_action_candidates",
    "normalize_for_player",
    "observation_from_player_state",
    "parse_showdown_replay",
    "iter_rollout_records",
    "read_rollout_records",
    "rollout_record_from_dict",
    "rollout_record_to_dict",
    "showdown_choice_for_action",
    "showdown_submission_for_action",
    "stable_category_id",
    "summarize_records",
    "switch_action_index_for_team_index",
    "switch_action_candidates",
]
