"""Behavioral factor suite for tracking how a checkpoint's *strategy* evolves over training.

Win-rate says whether a checkpoint is stronger; it does not say *how* it plays. This module
measures concrete behavioral factors and is designed to be re-run on every new checkpoint so
the trajectory of each factor tells a story ("switching propensity rose, then toxic-awareness
finally kicked in at 3M", etc.).

Every factor is scored against a SHARED, fixed corpus of real decision states, so the numbers
are directly comparable across checkpoints. The corpus is generated by fixed, checkpoint-
INDEPENDENT heuristic drivers (max-damage / simple / random) across many seeds and both seats,
so it never shifts under the checkpoints being graded. Keep the driver set and seeds fixed for
longitudinal comparisons.

Factors (v1):
  - switch_propensity  — mean P(switch) over states where a switch is legal, plus the rate the
    switch is the argmax. A raw behavioral fingerprint (rose ~5x from 500k to 1M).
  - toxic_switch       — counterfactual lift: engineer badly-poisoned toxic onto HEALTHY,
    poison-SUSCEPTIBLE active mons and measure how much P(switch) rises vs the untouched state.
    ~0 => the policy ignores toxic when deciding whether to bail. (Never applied to Poison/Steel
    mons, which are immune — that would be an impossible, out-of-distribution state.)
  - setup_usage        — over states where a setup move (Dragon Dance / Calm Mind / Swords Dance
    / Bulk Up) is legal, the probability mass the policy puts on setting up, and the argmax rate.
    Good setup timing is highly contextual, so this is measured over a WIDE corpus and split by
    board pressure (healthy vs low-HP active) as a crude appropriateness signal — a strong policy
    should set up more when healthy/safe than when pressured.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, replace
from typing import Any, Mapping, Sequence

from .actions import ACTION_COUNT, MOVE_ACTION_COUNT
from .dex import load_showdown_dex_cached
from .local_showdown import LocalShowdownConfig, LocalShowdownEnv
from .online_client import build_agent
from .neural_policy import evaluate_transformer_action_priors
from .policy import MaxDamagePolicy, RandomLegalPolicy, SimpleLegalPolicy
from .showdown import (
    NUMERIC_TOXIC_STAGE,
    SELF_POKEMON_TOKEN_OFFSET,
    observation_from_player_state,
    showdown_choice_for_action,
)

# The named sweep-setup moves. Configurable; these are the four the tracker was asked for.
DEFAULT_SETUP_MOVES = ("dragondance", "calmmind", "swordsdance", "bulkup")

# Poison-susceptible walls for the toxic counterfactual (see policy_probe.py for the rationale).
DEFAULT_STALLERS = (
    "vaporeon", "blissey", "suicune", "milotic", "snorlax",
    "slowbro", "umbreon", "regice", "lapras", "hypno",
)

# Toxic ramp depth used for the counterfactual lift (encoder saturates at 15 via the /15 norm).
TOXIC_DEEP_STAGE = 15

# Active mon HP fraction above which we call the board "healthy" (a safe-ish setup window).
HEALTHY_HP = 0.6


def norm(name: str) -> str:
    return "".join(ch for ch in str(name).lower() if ch.isalnum())


def hp_fraction(condition: str | None) -> float:
    parts = str(condition or "").split()
    if parts and "/" in parts[0]:
        num, _, den = parts[0].partition("/")
        try:
            return max(0.0, min(1.0, float(num) / float(den)))
        except (ValueError, ZeroDivisionError):
            return 0.0
    return 0.0


def hp_token(condition: str | None) -> str:
    parts = str(condition or "100/100").split()
    return parts[0] if parts else "100/100"


def active_status(condition: str | None) -> str:
    parts = str(condition or "").split()
    return next((p for p in parts[1:] if p != "fnt"), "none")


def toxic_immune(dex, species: str) -> bool:
    info = dex.species_info(species)
    types = info.types if info else ()
    return any(str(t).lower() in ("poison", "steel") for t in types)


def active_token_index(state) -> int:
    for offset, pokemon in enumerate(state.self_team):
        if pokemon.active:
            return SELF_POKEMON_TOKEN_OFFSET + offset
    raise RuntimeError("no active mon in self_team")


def engineer_toxic(state, stage: int | None):
    """Return a copy of `state` with the active mon badly poisoned at ramp `stage`
    (status:tox categorical + the NUMERIC_TOXIC_STAGE ramp + belief status), HP held fixed.
    `stage=None` clears the status (healthy baseline)."""
    active = state.self_active
    hp = hp_token(active.condition)
    status_word = "tox" if stage is not None else ""
    new_condition = f"{hp} {status_word}".strip()
    new_team = tuple(
        replace(p, condition=new_condition) if p is active else p for p in state.self_team
    )
    belief = state.belief_view
    new_self_belief = tuple(
        replace(b, status=("tox" if stage is not None else None), condition=new_condition)
        if b.active
        else b
        for b in belief.self_pokemon
    )
    new_belief = replace(belief, self_pokemon=new_self_belief)
    return replace(
        state, self_team=new_team, belief_view=new_belief, self_toxic_stage=(stage or 0)
    )


def _legal_setup_slots(state, setup_moves: frozenset[str]) -> tuple[tuple[int, str], ...]:
    """(action_index, move_id) for legal move slots whose move is a setup move."""
    request = state.request
    if not isinstance(request, Mapping):
        return ()
    active = request.get("active")
    first = active[0] if isinstance(active, (list, tuple)) and active else None
    moves = first.get("moves") if isinstance(first, Mapping) else None
    if not isinstance(moves, (list, tuple)):
        return ()
    mask = state.legal_action_mask
    out = []
    for slot in range(min(MOVE_ACTION_COUNT, len(moves))):
        if slot < len(mask) and not mask[slot]:
            continue
        entry = moves[slot]
        move_id = norm(entry.get("id") or entry.get("move") or "") if isinstance(entry, Mapping) else ""
        if move_id in setup_moves:
            out.append((slot, move_id))
    return tuple(out)


@dataclass
class CorpusEntry:
    state: Any
    seed: int
    player: str
    turn: int
    active_species: str
    active_status: str
    active_hp: float
    poison_susceptible: bool
    legal_switch: bool
    setup_slots: tuple[tuple[int, str], ...]


def _driver_pairs(showdown_root: str):
    """Fixed, checkpoint-independent driver pairings. max-damage gives realistic aggressive
    lines; random reaches wild states (incl. setup windows); simple exercises switching."""
    return (
        (MaxDamagePolicy(showdown_root=showdown_root), MaxDamagePolicy(showdown_root=showdown_root)),
        (MaxDamagePolicy(showdown_root=showdown_root), RandomLegalPolicy()),
        (SimpleLegalPolicy(), SimpleLegalPolicy()),
        (RandomLegalPolicy(), RandomLegalPolicy()),
    )


def build_corpus(
    showdown_root: str,
    *,
    num_games: int = 60,
    seed_start: int = 1,
    max_states: int = 800,
    setup_moves: Sequence[str] = DEFAULT_SETUP_MOVES,
) -> list[CorpusEntry]:
    """Play `num_games` self-play games with the fixed driver ensemble and collect real decision
    states (both seats) into a comparable corpus. Deterministic given (showdown_root, seeds)."""
    dex = load_showdown_dex_cached(showdown_root)
    setup_set = frozenset(norm(m) for m in setup_moves)
    pairs = _driver_pairs(showdown_root)
    entries: list[CorpusEntry] = []

    for index in range(num_games):
        seed = seed_start + index
        pair = pairs[index % len(pairs)]
        env = LocalShowdownEnv(LocalShowdownConfig(showdown_root=showdown_root))
        env.reset(seed=seed)
        rngs = {"p1": random.Random(seed * 2 + 1), "p2": random.Random(seed * 2 + 2)}

        for _ in range(400):
            if env.terminal() is not None:
                break
            requested = env.requested_players()
            for player in ("p1", "p2"):
                if player not in requested:
                    continue
                state = env._state_for_player(player)
                active = state.self_active
                if active is None or state.request_kind in {"wait", "none"}:
                    continue
                if not any(state.legal_action_mask):
                    continue
                entries.append(
                    CorpusEntry(
                        state=state,
                        seed=seed,
                        player=player,
                        turn=state.turn_number,
                        active_species=active.species,
                        active_status=active_status(active.condition),
                        active_hp=hp_fraction(active.condition),
                        poison_susceptible=not toxic_immune(dex, active.species),
                        legal_switch=any(state.legal_action_mask[MOVE_ACTION_COUNT:ACTION_COUNT]),
                        setup_slots=_legal_setup_slots(state, setup_set),
                    )
                )
            if len(entries) >= max_states:
                return entries
            actions = {}
            for player in requested:
                obs = env.observe(player)
                if not any(obs.legal_action_mask):
                    continue
                driver = pair[0] if player == "p1" else pair[1]
                actions[player] = driver.select_action(obs, rng=rngs[player]).action_index
            if not actions:
                break
            env.step(actions)
    return entries


def choice_label(state, action_index: int) -> str:
    """Human-readable label for a legal action: 'move:Surf' or 'switch:Blissey'."""
    choice = showdown_choice_for_action(state, action_index)
    kind, _, num = choice.partition(" ")
    if kind == "move":
        request = state.request if isinstance(state.request, Mapping) else {}
        active = request.get("active")
        first = active[0] if isinstance(active, (list, tuple)) and active else None
        moves = first.get("moves") if isinstance(first, Mapping) else None
        if isinstance(moves, (list, tuple)) and action_index < len(moves) and isinstance(moves[action_index], Mapping):
            display = moves[action_index].get("move") or moves[action_index].get("id") or choice
            return f"move:{display}"
        return choice
    if kind == "switch":
        team_index = int(num) - 1
        if 0 <= team_index < len(state.self_team):
            return f"switch:{state.self_team[team_index].species}"
    return choice


def sample_states_at_turn(
    showdown_root: str,
    *,
    num_games: int = 25,
    turn: int = 10,
    player: str = "p1",
    seed_start: int = 1,
    max_seed_scan: int | None = None,
):
    """Collect one decision state per unique game at the given turn (deterministic driver ensemble).
    Returns a list of (state, seed). Games that end before `turn` (or have no clean decision for
    `player` there) are skipped and the next seed is tried, up to `max_seed_scan` seeds."""
    pairs = _driver_pairs(showdown_root)
    scan_limit = max_seed_scan if max_seed_scan is not None else num_games * 8
    collected: list[tuple[Any, int]] = []

    for offset in range(scan_limit):
        if len(collected) >= num_games:
            break
        seed = seed_start + offset
        pair = pairs[offset % len(pairs)]
        env = LocalShowdownEnv(LocalShowdownConfig(showdown_root=showdown_root))
        env.reset(seed=seed)
        rngs = {"p1": random.Random(seed * 2 + 1), "p2": random.Random(seed * 2 + 2)}
        captured = None

        for _ in range(400):
            if env.terminal() is not None:
                break
            requested = env.requested_players()
            if player in requested:
                state = env._state_for_player(player)
                if (
                    state.turn_number == turn
                    and state.request_kind not in {"wait", "none"}
                    and any(state.legal_action_mask)
                ):
                    captured = state
                    break
                if state.turn_number > turn:
                    break  # missed the window this game
            actions = {}
            for member in requested:
                obs = env.observe(member)
                if not any(obs.legal_action_mask):
                    continue
                driver = pair[0] if member == "p1" else pair[1]
                actions[member] = driver.select_action(obs, rng=rngs[member]).action_index
            if not actions:
                break
            env.step(actions)

        if captured is not None:
            collected.append((captured, seed))
    return collected


def _mean(values: Sequence[float]) -> float:
    return round(sum(values) / len(values), 4) if values else 0.0


def evaluate_checkpoint(label: str, checkpoint: str, showdown_root: str, corpus: Sequence[CorpusEntry]):
    """Score every factor for one checkpoint against the shared corpus."""
    agent = build_agent(checkpoint, showdown_root, our_name="factors", deterministic=True)

    def priors(state):
        obs = observation_from_player_state(
            state, category_vocab=agent.vocab, spec=agent.spec, dex=agent.dex
        )
        return evaluate_transformer_action_priors(
            model=agent.policy.model, result=agent.policy.result, observations=[obs]
        )

    switch_probs: list[float] = []
    switch_argmax = 0
    setup_mass = {"healthy": [], "pressured": []}
    setup_argmax = 0
    setup_states = 0
    setup_by_move: dict[str, list[float]] = {}
    toxic_deltas: list[float] = []

    for entry in corpus:
        probs = priors(entry.state)
        argmax = max(range(ACTION_COUNT), key=lambda i: probs[i])

        if entry.legal_switch:
            switch_probs.append(sum(probs[MOVE_ACTION_COUNT:ACTION_COUNT]))
            if argmax >= MOVE_ACTION_COUNT:
                switch_argmax += 1

        if entry.setup_slots:
            slot_indices = {slot for slot, _ in entry.setup_slots}
            mass = sum(probs[slot] for slot in slot_indices)
            band = "healthy" if entry.active_hp > HEALTHY_HP else "pressured"
            setup_mass[band].append(mass)
            setup_states += 1
            if argmax in slot_indices:
                setup_argmax += 1
            for slot, move_id in entry.setup_slots:
                setup_by_move.setdefault(move_id, []).append(probs[slot])

        # Toxic counterfactual: only on healthy, poison-susceptible mons that can actually bail.
        if entry.poison_susceptible and entry.legal_switch and entry.active_status == "none":
            base = sum(probs[MOVE_ACTION_COUNT:ACTION_COUNT])
            tox_probs = priors(engineer_toxic(entry.state, TOXIC_DEEP_STAGE))
            toxic_deltas.append(sum(tox_probs[MOVE_ACTION_COUNT:ACTION_COUNT]) - base)

    return {
        "label": label,
        "checkpoint": checkpoint,
        "switch_propensity": {
            "mean_p_switch": _mean(switch_probs),
            "argmax_switch_rate": round(switch_argmax / len(switch_probs), 4) if switch_probs else 0.0,
            "n_states": len(switch_probs),
        },
        "toxic_switch": {
            "mean_lift": _mean(toxic_deltas),
            "n_states": len(toxic_deltas),
        },
        "setup_usage": {
            "mean_mass_healthy": _mean(setup_mass["healthy"]),
            "mean_mass_pressured": _mean(setup_mass["pressured"]),
            "argmax_setup_rate": round(setup_argmax / setup_states, 4) if setup_states else 0.0,
            "by_move": {m: {"mean_p": _mean(v), "n": len(v)} for m, v in sorted(setup_by_move.items())},
            "n_states": setup_states,
        },
    }
